### PR TITLE
Add dependency for keycloak adapters.

### PR DESCRIPTION
**Pull request by RadekKoubsky**

### CODE REVIEW

**Comment by cmoulliard** [comment]
Can you also include the dependencies defined for the SSO mission please 

```
        <!-- KeyCloak -->
        <dependency>
            <groupId>org.keycloak</groupId>
            <artifactId>keycloak-adapter-spi</artifactId>
        </dependency>
        <dependency>
            <groupId>org.keycloak</groupId>
            <artifactId>keycloak-tomcat8-adapter</artifactId>
        </dependency>
        <dependency>
            <groupId>org.keycloak</groupId>
            <artifactId>keycloak-spring-boot-adapter</artifactId>
        </dependency>
```

**Comment by RadekKoubsky** [comment]
I replaced (tested) the keycloak-adapters-pom with specific adapters dependencies as Michal said that the keycloak-adapters-pom is not productized (in case we want to change keycloak adapters to productized versions).

**Comment by michalszynkiewicz** [comment]
The newest productized version of keycloak is 2.5.7 (there's no community one for it, for Swarm we use 2.5.5).
@cmoulliard Radek says boosters use 1.9.8, do you know why we are on such an old version there? Should we upgrade it?

**Comment by cmoulliard** [comment]
> old version

This is because the SSO OpenShift template that we have started use to deploy Keycloak on OpenShift was based on this old version. 

As now the sso mission uses SSO 7.1 (https://goo.gl/FVBA8X -> rh-sso 7.1.0.GA -> WildFly Core 2.1.15.Final-redhat-1), we could bump to 2.1.15.Final

**Comment by RadekKoubsky** [comment]
@cmoulliard @michalszynkiewicz have we decided what version of keycloak are we going to use? I can retest the sso booster before merging this PR and releasing the BOM.

**Comment by cmoulliard** [comment]
@RadekKoubsky According to my comment, you can use : 2.1.15.Final

**Comment by RadekKoubsky** [comment]
Where did you find that version of keycloak? I have looked into maven central and jboss repository, found only 2.0.0.Final or 2.1.0.Final, for instance [keycloak-spring-boot-adapter](http://maven.repository.redhat.com/nexus/content/repositories/public-jboss/org/keycloak/keycloak-spring-boot-adapter/)

If we speak about the [sso71-openshift](https://access.redhat.com/containers/?tab=tech-details#/registry.access.redhat.com/redhat-sso-7/sso71-openshift) image, it uses SSO 7.1.0 that is based on Keycloak 2.5.5.Final

**Comment by cmoulliard** [comment]
errare humanum est. The version I added is the version of WildFly. So the correct one is : Keycloak 2.5.5.Final

**Comment by RadekKoubsky** [comment]
I have tested the spring-boot sso booster, works fine.

**Pull request merged**
